title: Justicia situada
description: Un proyecto de justicia situada, violencia interseccional y epistemologías críticas desde el Sur Global.
baseurl: "/justicia-situada"
url: "https://llasmani.github.io"
theme: minima
