title: Justicia situada
description: Un proyecto de justicia situada, violencia interseccional y epistemologías críticas desde el Sur Global.
baseurl: ""
url: "https://llasmani.github.io/justicia-situada"
theme: minima
